# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DNN.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DNN.proto',
  package='myDNN',
  syntax='proto2',
  serialized_pb=_b('\n\tDNN.proto\x12\x05myDNN\"\xca\x01\n\x03Net\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nnum_layers\x18\x02 \x02(\x05\x12 \n\x06layers\x18\x03 \x03(\x0b\x32\x10.myDNN.Net.Layer\x1a[\n\x05Layer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x02\x42\x02\x10\x01\x12#\n\x04type\x18\x04 \x01(\x0e\x32\x0f.myDNN.Net.Type:\x04MISC\"\"\n\x04Type\x12\x08\n\x04MISC\x10\x00\x12\x08\n\x04\x43ONV\x10\x01\x12\x06\n\x02\x46\x43\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NET_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='myDNN.Net.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MISC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FC', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_NET_TYPE)


_NET_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='myDNN.Net.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='myDNN.Net.Layer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='myDNN.Net.Layer.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='myDNN.Net.Layer.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='type', full_name='myDNN.Net.Layer.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=187,
)

_NET = _descriptor.Descriptor(
  name='Net',
  full_name='myDNN.Net',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='myDNN.Net.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_layers', full_name='myDNN.Net.num_layers', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layers', full_name='myDNN.Net.layers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NET_LAYER, ],
  enum_types=[
    _NET_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=223,
)

_NET_LAYER.fields_by_name['type'].enum_type = _NET_TYPE
_NET_LAYER.containing_type = _NET
_NET.fields_by_name['layers'].message_type = _NET_LAYER
_NET_TYPE.containing_type = _NET
DESCRIPTOR.message_types_by_name['Net'] = _NET

Net = _reflection.GeneratedProtocolMessageType('Net', (_message.Message,), dict(

  Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
    DESCRIPTOR = _NET_LAYER,
    __module__ = 'DNN_pb2'
    # @@protoc_insertion_point(class_scope:myDNN.Net.Layer)
    ))
  ,
  DESCRIPTOR = _NET,
  __module__ = 'DNN_pb2'
  # @@protoc_insertion_point(class_scope:myDNN.Net)
  ))
_sym_db.RegisterMessage(Net)
_sym_db.RegisterMessage(Net.Layer)


_NET_LAYER.fields_by_name['data'].has_options = True
_NET_LAYER.fields_by_name['data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
